import type { FinancialWidgetDefinition, WidgetCategory } from "../types/widgets";

/** Display order for Customize Dashboard category groups. */
export const WIDGET_CATEGORY_ORDER: WidgetCategory[] = [
  "overview",
  "income",
  "spending",
  "budgeting",
  "cash_flow",
  "expenses",
  "goals",
  "planning",
];

export const WIDGET_CATEGORY_LABELS: Record<WidgetCategory, string> = {
  overview: "Overview",
  income: "Income",
  spending: "Spending",
  budgeting: "Budgeting",
  cash_flow: "Cash Flow",
  expenses: "Expenses",
  goals: "Goals",
  planning: "Planning",
};

/**
 * Canonical educational metadata for every existing dashboard widget.
 * Presentation (render/preview) stays in App; this is product knowledge only.
 */
export const WIDGET_CATALOG: FinancialWidgetDefinition[] = [
  {
    id: "stat-balance",
    name: "Balance",
    category: "overview",
    shortDescription: "Your current net position across accounts.",
    whatItShows: "The combined balance from the accounts and transactions you have on file.",
    whyItMatters: "A clear balance helps you see whether you are ahead or behind before looking at individual categories.",
    financialPlanningUses: [
      "Check overall position at a glance",
      "Compare against upcoming bills",
      "Ground cash-flow decisions in a real number",
    ],
    dataRequirements: ["accounts", "transactions", "starting balance"],
    supportedInsights: ["cash_flow_pattern", "positive_pattern", "attention_needed"],
    supportedActions: ["dashboard", "transactions", "networth"],
    assessmentSignals: ["has_accounts", "has_balance"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "Where do I stand right now?",
  },
  {
    id: "stat-money-in",
    name: "In today",
    category: "income",
    shortDescription: "Income recorded for today.",
    whatItShows: "Money that came in today from paychecks, transfers, or other income you logged.",
    whyItMatters: "Seeing today's inflow helps you connect deposits to spending power without waiting for a monthly report.",
    financialPlanningUses: [
      "Confirm a paycheck landed",
      "Track same-day income",
      "Pair with Out today for a daily net",
    ],
    dataRequirements: ["income transactions"],
    supportedInsights: ["income_summary"],
    supportedActions: ["transactions", "calendar"],
    assessmentSignals: ["has_income"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "What came in today?",
  },
  {
    id: "stat-money-out",
    name: "Out today",
    category: "spending",
    shortDescription: "Expenses recorded for today.",
    whatItShows: "Money that left your accounts today through expenses, bills, or transfers out.",
    whyItMatters: "Daily outflow awareness catches overspending early, before it shows up as a surprise at month end.",
    financialPlanningUses: [
      "Monitor same-day spending",
      "Spot unusual charges quickly",
      "Pair with In today for a daily net",
    ],
    dataRequirements: ["expense transactions"],
    supportedInsights: ["spending_pattern", "attention_needed"],
    supportedActions: ["transactions", "spending"],
    assessmentSignals: ["has_flexible_spending", "has_transactions"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "What went out today?",
  },
  {
    id: "stat-savings",
    name: "Savings",
    category: "goals",
    shortDescription: "Total saved toward your goals.",
    whatItShows: "The combined amount saved across the goals you have set up.",
    whyItMatters: "Goals need a visible total so progress feels real and contributions stay intentional.",
    financialPlanningUses: [
      "Track goal progress at a glance",
      "Motivate contribution increases",
      "See savings separate from checking balance",
    ],
    dataRequirements: ["goals"],
    supportedInsights: ["goal_opportunity"],
    supportedActions: ["goals"],
    assessmentSignals: ["has_goals"],
    defaultVisibility: "optional",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "How much have I saved toward goals?",
  },
  {
    id: "stat-monthly-net",
    name: "Monthly Net",
    category: "cash_flow",
    shortDescription: "Income minus expenses for the month.",
    whatItShows: "A snapshot of whether this month is running ahead or behind overall.",
    whyItMatters: "Net cash flow shows whether your plan is sustainable before looking at individual categories.",
    financialPlanningUses: [
      "Judge month-to-date health",
      "Decide if you can increase savings",
      "Spot a shortfall early",
    ],
    dataRequirements: ["income", "expenses"],
    supportedInsights: ["cash_flow_pattern", "positive_pattern", "attention_needed"],
    supportedActions: ["budget", "transactions"],
    assessmentSignals: ["has_income", "negative_cash_flow", "positive_cash_flow"],
    defaultVisibility: "optional",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "Am I ahead or behind this month?",
  },
  {
    id: "stat-weekly-spend",
    name: "Weekly Spend",
    category: "spending",
    shortDescription: "How much you have spent this week.",
    whatItShows: "Total spending for the current week from logged transactions.",
    whyItMatters: "A weekly spend total keeps flexible spending visible between paychecks.",
    financialPlanningUses: [
      "Stay aware of mid-week spending",
      "Compare against weekly spending power",
      "Catch category spikes early",
    ],
    dataRequirements: ["expense transactions"],
    supportedInsights: ["spending_pattern"],
    supportedActions: ["spending", "transactions"],
    assessmentSignals: ["has_flexible_spending", "high_flexible_spending"],
    defaultVisibility: "optional",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "How much have I spent this week?",
  },
  {
    id: "stat-remaining",
    name: "Budget Remaining",
    category: "budgeting",
    shortDescription: "Budget left for the month across categories.",
    whatItShows: "How much of your planned category budgets is still available this month.",
    whyItMatters: "Remaining budget is the practical signal for whether you can spend freely or need to slow down.",
    financialPlanningUses: [
      "Decide if a purchase fits the plan",
      "See which categories still have room",
      "Avoid overspending late in the month",
    ],
    dataRequirements: ["budgets", "category spending"],
    supportedInsights: ["spending_pattern", "attention_needed"],
    supportedActions: ["budget"],
    assessmentSignals: ["has_budgets"],
    defaultVisibility: "optional",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "How much budget is left?",
  },
  {
    id: "weekly-power",
    name: "Weekly spending power",
    category: "overview",
    shortDescription: "How much room you have to spend this week after known bills.",
    whatItShows: "Your available weekly budget after accounting for bills and spending already on file.",
    whyItMatters: "Spending power turns abstract budgets into a practical weekly number you can act on.",
    financialPlanningUses: [
      "Decide what you can afford this week",
      "Pace spending between paychecks",
      "Connect bills to everyday choices",
    ],
    dataRequirements: ["weekly budget", "bills", "weekly spending"],
    supportedInsights: ["cash_flow_pattern", "positive_pattern", "attention_needed"],
    supportedActions: ["dashboard", "budget", "calendar"],
    assessmentSignals: ["has_income", "has_obligations", "cash_flow_visibility"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "How much room do I have?",
  },
  {
    id: "daily-limit",
    name: "Daily spending limit",
    category: "budgeting",
    shortDescription: "A daily pace to stay within this week's plan.",
    whatItShows: "An estimated daily amount that helps you stay on track for the rest of the week.",
    whyItMatters: "Breaking weekly room into a daily limit makes it easier to say yes or no to everyday purchases.",
    financialPlanningUses: [
      "Pace discretionary spending day by day",
      "Avoid burning the weekly budget early",
      "Build a simple spending rhythm",
    ],
    dataRequirements: ["weekly spending power"],
    supportedInsights: ["spending_pattern"],
    supportedActions: ["budget", "spending"],
    assessmentSignals: ["high_flexible_spending", "spending_awareness"],
    defaultVisibility: "optional",
    customizable: true,
    tourEligible: false,
    primaryQuestion: "What can I spend today?",
  },
  {
    id: "balance-chart",
    name: "Balance",
    category: "cash_flow",
    shortDescription: "How your balance has moved over time.",
    whatItShows: "Daily ending balances across a range you choose, optionally filtered by account.",
    whyItMatters: "A balance timeline reveals timing pressure that a single number cannot show.",
    financialPlanningUses: [
      "See dips before big bills",
      "Compare account trajectories",
      "Understand paycheck-to-paycheck swings",
    ],
    dataRequirements: ["accounts", "transactions", "scheduled items"],
    supportedInsights: ["cash_flow_pattern", "income_timing_mismatch"],
    supportedActions: ["calendar", "transactions"],
    assessmentSignals: ["cash_flow_visibility", "has_transactions"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "When is money coming in and going out?",
  },
  {
    id: "monthly-spend-chart",
    name: "Spending Trend",
    category: "spending",
    shortDescription: "How your spending is changing month to month.",
    whatItShows: "Total spending across recent months so you can see direction, not just one month's total.",
    whyItMatters: "Trends show whether spending is rising, falling, or stable — the signal behind category noise.",
    financialPlanningUses: [
      "Spot rising spending early",
      "Compare seasons or months",
      "Validate that budget changes are working",
    ],
    dataRequirements: ["expense transactions"],
    supportedInsights: ["spending_pattern"],
    supportedActions: ["spending", "budget"],
    assessmentSignals: ["has_flexible_spending", "spending_awareness"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "How is my spending changing?",
  },
  {
    id: "spending-breakdown",
    name: "Spending Breakdown",
    category: "spending",
    shortDescription: "Where your money is going across categories.",
    whatItShows: "Your spending by category for a period you choose, with share of the total.",
    whyItMatters: "Understanding where money goes helps you decide what to protect, trim, or redirect toward goals.",
    financialPlanningUses: [
      "Understand spending habits",
      "Identify high-spending categories",
      "Compare spending over time",
      "Find opportunities to redirect money toward goals",
    ],
    dataRequirements: ["expense transactions", "categories"],
    supportedInsights: ["spending_pattern", "largest_expense", "category_concentration"],
    supportedActions: ["spending", "budget"],
    assessmentSignals: ["has_flexible_spending", "high_flexible_spending", "category_concentration"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "Where is my money going?",
  },
  {
    id: "budget-remaining",
    name: "Budget Health",
    category: "budgeting",
    shortDescription: "Whether categories are staying within plan.",
    whatItShows: "Progress against category budgets, highlighting the categories closest to their limits.",
    whyItMatters: "Budget health turns category limits into a living plan you can adjust before overspending sticks.",
    financialPlanningUses: [
      "Stay within category plans",
      "Reallocate unused budget",
      "Act on categories that are running hot",
    ],
    dataRequirements: ["budgets", "category spending"],
    supportedInsights: ["spending_pattern", "attention_needed"],
    supportedActions: ["budget"],
    assessmentSignals: ["has_budgets", "budget_organization"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "Am I staying within my plan?",
  },
  {
    id: "next-paycheck",
    name: "Next Paycheck",
    category: "income",
    shortDescription: "When money is coming in next and what that does to balance.",
    whatItShows: "Your next upcoming income date and amount, plus the projected balance after it lands.",
    whyItMatters: "Income timing drives when you can safely spend; seeing the next paycheck reduces payday anxiety.",
    financialPlanningUses: [
      "Plan spending until payday",
      "Anticipate balance after income",
      "Coordinate bill due dates with pay days",
    ],
    dataRequirements: ["income streams or income transactions"],
    supportedInsights: ["income_summary", "cash_flow_pattern"],
    supportedActions: ["calendar", "transactions"],
    assessmentSignals: ["has_income", "income_organization"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "Where is my money coming from next?",
  },
  {
    id: "savings-goal",
    name: "Savings Goals",
    category: "goals",
    shortDescription: "Progress toward the goals you are saving for.",
    whatItShows: "Each goal's saved amount, target, and completion progress.",
    whyItMatters: "Goals give surplus cash a purpose; progress bars keep that purpose visible on the dashboard.",
    financialPlanningUses: [
      "Track progress toward targets",
      "Decide contribution amounts",
      "Prioritize among multiple goals",
    ],
    dataRequirements: ["goals"],
    supportedInsights: ["goal_opportunity"],
    supportedActions: ["goals"],
    assessmentSignals: ["has_goals", "goal_underfunding", "excess_cash_flow"],
    defaultVisibility: "optional",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "Am I moving toward my goal?",
  },
  {
    id: "biggest-bill",
    name: "Largest Upcoming Bill",
    category: "expenses",
    shortDescription: "The next bills that matter most.",
    whatItShows: "Your nearest upcoming bills, led by the next due amount and date.",
    whyItMatters: "Upcoming obligations create cash-flow pressure; seeing them early prevents shortfalls.",
    financialPlanningUses: [
      "Prepare for large due dates",
      "Review recurring obligations",
      "Align spending with bill timing",
    ],
    dataRequirements: ["bills"],
    supportedInsights: ["upcoming_obligation", "largest_expense"],
    supportedActions: ["bills", "calendar", "budget"],
    assessmentSignals: ["has_obligations", "upcoming_expense_pressure", "high_recurring_obligations"],
    defaultVisibility: "core",
    customizable: true,
    tourEligible: true,
    primaryQuestion: "What do I need to pay soon?",
  },
];

const byId = new Map(WIDGET_CATALOG.map((w) => [w.id, w]));

export function getWidgetDefinition(id: string): FinancialWidgetDefinition | undefined {
  return byId.get(id);
}

export function listWidgetsByCategory(category: WidgetCategory): FinancialWidgetDefinition[] {
  return WIDGET_CATALOG.filter((w) => w.category === category);
}

export function coreWidgetIds(): string[] {
  return WIDGET_CATALOG.filter((w) => w.defaultVisibility === "core").map((w) => w.id);
}

export function tourEligibleWidgetIds(): string[] {
  return WIDGET_CATALOG.filter((w) => w.tourEligible).map((w) => w.id);
}
